apiVersion: v1
kind: Secret
metadata:
    name: boobs-bot-notifier-secret
    namespace: dev-developers-bot
type: Opaque
stringData:
    token: <token>
    ids: <ids-comma-separated>

---

apiVersion: batch/v1
kind: CronJob
metadata:
  name: boobs-bot-notifier
  namespace: dev-developers-bot
spec:
  schedule: "0 10 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: boobs-bot-notifier
        spec:
          containers:
          - name: boobs-bot-notifier
            image: abawer/ahmed-bot:latest
            imagePullPolicy: Always
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            env:
              - name: TOKEN
                valueFrom:
                  secretKeyRef:
                    name: boobs-bot-notifier-secret
                    key: token
              - name: CHAT_IDS
                valueFrom:
                  secretKeyRef:
                    name: boobs-bot-notifier-secret
                    key: ids
            resources:
              requests:
                memory: "256Mi"
                cpu: "0.2"
              limits:
                memory: "1024Mi"
                cpu: "1"
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          terminationGracePeriodSeconds: 30
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1

