name: Trigger for bot

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  build:
    name: bot
    runs-on: ubuntu-latest
    steps:
      - run: docker run -e TOKEN=${{ secrets.TOKEN}} 
            -e CHAT_IDS=${{ secrets.CHAT_IDS }} 
            -e reddit_clientid=${{ secrets.REDDIT_CLIENTID }}
            -e reddit_secret=${{ secrets.REDDIT_CLIENTID }}
            -e subs_list=${{ secrets.SUBS_LIST }}
            --rm ${{ secrets.DOCKER_IMAGE_NAME }}